/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */


export const projectId = "ojgdtznzmjcjonazstqg" // Keeping project ID just in case, though URL is usually enough
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;